### ISSUE TITLE
What's the difference between Neighbor Connection Decoder (NCD) and Cascade Partial Decoder (CPD) ? 

### ISSUE THREAD

**Issue by ArthurRyan0803** [GewelsJI/SINet-V2#5]
I found that they are almost the same...

### [CPD: ](https://github.com/wuzhe71/CPD/blob/master/model/CPD_models.py)
![CPD](https://user-images.githubusercontent.com/38326748/170010768-5f8f0105-a418-4dd8-8f9d-5ecb73a56840.png)

### [NCD:](https://github.com/GewelsJI/SINet-V2/blob/main/lib/Network_Res2Net_GRA_NCD.py)
![NCD](https://user-images.githubusercontent.com/38326748/170010615-6be2b7af-010c-4b3d-a6df-62374a702c3f.png)

**Comment by GewelsJI** [comment]
Hi, 

Sorry for the quick reply yesterday due to my busy time. First, thank you for your attention to our work. 

Their differences and effectiveness have been discussed in our paper. Notably, based on the partial decoder presented in CPD, we take a small but effective change on it. 

**Motivation:** As observed by CPD, low-level features consume more computational resources due to their larger spatial resolutions but contribute less to performance. Motivated by this observation, we decide to aggregate only the top-three highest-level features via a new decoding strategy.

**Existing Issues:** There are still two key issues when aggregating multiple feature pyramids; namely, how to maintain semantic consistency within a layer and how to bridge the context across layers. 

**How to address it?** Here, we propose to address these with the neighbor connection decoder (NCD). More specifically, we modify the partial decoder component (PDC) with a neighbor connection function and get three refined features. Here is the comparison with previous decoding strategies:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/38354957/170284595-2dcbde48-f08f-4467-9fe3-4e692a548889.png">

For more discussions and experimental verifications, please refer to our original paper. Hope you are doing well.

Best regards,
Ge-Peng Ji.
